= Заметки
:toc: left
:icons: font

== Bash
=== Скрыть юзернейм и&nbsp;хостнейм

Например, чтобы делать скриншоты и&nbsp;скринкасты для документации.

Приглашение баша определяется переменной `PS1`.
Чтобы скрыть имя пользователя и&nbsp;хост, но&nbsp;оставить текущее местоположение,
можно указать такой формат:

    PS1="\\w \$ "

Пример вывода:

```
~ $
~ $
~ $ cd folder/
~/folder $
~/folder $ cd anotherFolder
~/folder/anotherFolder $
```

Чтобы без лишних настроек получить чистое окно консоли:

    PS1="\\w \$ ";clear

Переменную `PS1` можно определить в `~/.bashrc`.
https://gahcep.github.io/blog/2012/07/28/unix-bash-shell-prompt/[Подробнее об&nbsp;этой переменной].

=== Освободить место

Когда забивается диск, перестают работать
самые базовые вещи. Даже клавиша TAB в&nbsp;баше.
Ничего нельзя доустановить, чтобы решить проблему.

Поэтому NCurses Disk Usage лучше устанавливать сразу после развёртывания сервера.

    sudo apt-get install ncdu

Программа рекурсивно сканирует папки и&nbsp;сортирует их
в&nbsp;порядке убывания размера.
Навигация как в&nbsp;mc, выход&nbsp;— q.

Когда место кончится:

. `df -h` чтобы понять, какие разделы переполнены.
. `ncdu` _из&nbsp;точки монтирования нужного раздела._

[NOTE]
====
Команда сканирует текущую директорию (working directory).
====

=== Подсветка синтаксиса в&nbsp;less

В Ubuntu:

    sudo apt install source-highlight

Затем в `$HOME/.bashrc` добавить

```
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R -N'
```

[WARNING]
====
При открывании больших файлов могут появиться существенные задержки.
====

Опция `-N` необязательна. Она добавляет номера строк.

=== Шпаргалка по nano

Чтобы видеть номер текущей строки при редактировании:

    nano -c file.txt

Комбинации клавиш:

* Вырезать строку&nbsp;— CTRL+K.
* Вставить строку&nbsp;— CTRL+U.
* Undo&nbsp;— ALT+U или Esc+U (под M в справке подразумевается https://en.wikipedia.org/wiki/Meta_key[клавиша meta]).
* Redo&nbsp;— ALT+E или Esc+E.

=== Сканирование портов

Иногда nmap не может просканировать порты, т.к. устройство игнорирует пинг.

Там есть опция `-Pn`, чтобы не пинговать перед сканированием.

В строчке ниже сканируются порты с&nbsp;первого по&nbsp;сотый.

    nmap -p 1-100 -Pn 192.168.1.1

=== Бэкапы для несекретной информации

Должны обладать:

	- избыточностью;
	- простым чтением и&nbsp;навигацией;
	- простотой в&nbsp;удалении старых снапшотов.

Предлагаю использовать cron и&nbsp;tar.

На&nbsp;инстансе, откуда делаются бэкапы, _из-под рута_ настраивается
https://serverfault.com/questions/255084/simple-rsync-in-crontab-without-password[безпарольный доступ]
к&nbsp;файл-серверу по&nbsp;SSH.

Полагаю, если:

- файл-сервер находится в&nbsp;локальной сети,
- cron-задача на&nbsp;клиенте настроена из-под рута,
- приватный ключ на&nbsp;клиенте защищен от&nbsp;чтения другими пользователями,

то приватный ключ можно делать без парольной фразы.

Открытый ключ копируется на _сервер_ в _файл_ /home/USER/.ssh/authorized_keys.

Права:

    drwx------ (700) user user .ssh
    -rw------- (600) user user .ssh/authorized_keys

Может потребоваться изменить настройки SSH-сервера (разрешить publickey- или RSA-аутентификацию).
И&nbsp;нужно сделать reload SSH-сервера.

Затем, например, в `/usr/local/bin` клиента кладём скрипт
с&nbsp;правами `700 root:root` примерно следующего содержания:

    #!/bin/sh
    tar -cvpz --one-file-system -C "/путь/к/папке/" папка | ssh логин@сервер "(cat > /бэкапы/`date +\"%Y-%m-%dT%H.%M.%S\"`-названиеПапки.tar.gz)"

`sudo crontab -u root -e`

    0 0,6,12,18 * * * /usr/local/bin/myScript.sh

Проблема, которая тут может возникнуть — закончится место на файл-сервере.
В моём случае, это несущественно. Буду удалять старые снапшоты вручную время от времени.

== Параллели между информатикой, психологией и&nbsp;философией

Посмотрел, я, значит, видосы Александра Гельевича.

=== Объектно-ориентированная онтология

Как будто бы усредненное ООП переписано в&nbsp;филосовских терминах.
Надо почитать «Спекулятивный реализм. введение» — книгу четырех авторов, родившихся примерно
в&nbsp;одно время с&nbsp;Симулой и&nbsp;Смоллтолком. Но&nbsp;боюсь, что чтобы понять эту книгу,
надо вначале понять всё, что было до&nbsp;неё в&nbsp;философии.
Наверно у&nbsp;меня не&nbsp;хватит на&nbsp;это терпения.

Из краткого изложения пока видны такие параллели.

Программисты, операторы ЭВМ, пользователи обладают https://ru.wikipedia.org/wiki/Dasein[дазайном].
Например, когда программист описывает класс или объект, он описывает его, как он о&nbsp;нём мыслит,
https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D1%82%D0%B5%D0%BD%D1%86%D0%B8%D1%8F[направляя] на него своё внимание.
И&nbsp;объект описывается не&nbsp;как пассивный инструмент,
а&nbsp;как совершающий действия с&nbsp;собой и&nbsp;другими объектами субъект.
С&nbsp;помощью дазайна объекты вообще могут быть описаны, но&nbsp;существуют они отдельно от&nbsp;него.

Причем отказ от&nbsp;владения объектами происходит как со&nbsp;стороны программистов,
так и&nbsp;со&nbsp;стороны объектов по&nbsp;отношению друг к другу.

* GC позволяет не&nbsp;заботиться о&nbsp;местоположении объекта программисту.
Получается, что у C{plus}{plus}-программистов сильный контролирующий объекты дазайн.
Это выражается и&nbsp;в&nbsp;дизайне языка, и&nbsp;в&nbsp;практиках, которые для них характерны: контроль положения
структур в памяти (в т.ч. одних в&nbsp;других), unique_ptr, отказ от unit-тестов, аргументируя это
непогрешимостью программиста.
Т.е. C{plus}{plus}-программист «удерживает» программу своим человеческим сознанием,
не&nbsp;давая ей высвободиться.
Более современные практики концентрируются на&nbsp;том, чтобы программа сама контролировала
свою корректность, и&nbsp;как программа, так и&nbsp;ее части (объекты, модули) существовали настолько автономно,
насколько это возможно.
* IoC-контейнеры позволяют не «мыслить» одному конституированному
https://iphlib.ru/library/collection/newphilenc/document/HASH0124a45727a14304d1c56924[[1\]]
http://www.philosophydic.ru/konstituirovanie[[2\]]
объекту о&nbsp;другом как о&nbsp;подчиненном или включенном в&nbsp;себя.
Получается, что «слабость» дазайна разработчика передаётся описываемым им объектам,
и&nbsp;их&nbsp;субъектность также получается слабой по&nbsp;отношению уже к&nbsp;другим объектам.
* Обмен сообщениями позволяет не&nbsp;только асинхронность, но и&nbsp;сделать адресатов неизвестными,
и&nbsp;отправка сообщения в&nbsp;«тему» становится криком в&nbsp;пустоту.
Это еще большая отделённость объекта от&nbsp;субъекта.
* Слабая
https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D1%86%D0%B5%D0%BF%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)[связанность]
кода относится и&nbsp;к&nbsp;разработчику как к&nbsp;части кода.
* А&nbsp;у&nbsp;оператора ЭВМ не&nbsp;так&nbsp;уж важно наличие дазайна вообще для функционирования систем.

Т.е. тенденция ослабления дазайна в&nbsp;информатике очевидна, но и его существование также необходимо,
т.к. только через него объекты могут быть описаны. Если, конечно, я правильно понял все эти термины.

=== Шизоанализ

В&nbsp;психологии под виртуальным реальным подразумевается не&nbsp;то,
что мы обычно называем виртуальной реальностью,
а&nbsp;реальное, представленное в психике, поэтому оно виртуальное.

В&nbsp;шизоанализе Феликса Гваттари, виртуальное реальное (экзистенциальная территория)&nbsp;—
это психотический хаос в психике, ощущаемый, переживаемый непосредственно.
Т.е. он включает в&nbsp;себя всё ощущаемое, даже иллюзии, фантазии, видения, _находящиеся здесь_.
Человек выделяет из&nbsp;него некоторые структуры, называемые универсумами.
Это платоновские идеи наоборот. Не&nbsp;идеи предшествующие вещам, а&nbsp;идеи выделяемые из&nbsp;территории,
псевдо-вечные понятия, т.е. некоторые обобщения.
Затем эти универсумы могут быть выражены в&nbsp;абстрактных машинах.

Так вот, например, программист выражает универсумы в&nbsp;виде абстрактных машин и, возможно,
создаёт новые универсумы из&nbsp;переживаемого хаоса.

В&nbsp;лекциях много раз упоминается частичные объекты, но не&nbsp;вполне ясно, о&nbsp;чем идёт речь.
Вначале он называл так понятие https://fr.wikipedia.org/wiki/Objet_(psychanalyse)#Objet_partiel[part-object],
введенное последователями https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D1%8F%D0%B9%D0%BD,_%D0%9C%D0%B5%D0%BB%D0%B0%D0%BD%D0%B8[Мелани Кляйн],
затем он называет это https://en.wikipedia.org/wiki/Comfort_object[транзитивными объектами] и&nbsp;частями без целого,
будто&nbsp;бы насмехаясь над
https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B4%D1%83%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D0%B7%D0%BC[редукционизмом].
Обратил внимание, что в&nbsp;абсолютном большинстве современных языков, все объекты&nbsp;—
части, предшествующие целому, изначально не&nbsp;являющиеся частью ничего:
существуют в&nbsp;куче, соединяются через указатели.

Кстати, выражение универсумов на&nbsp;обычном человеческом языке&nbsp;— это ведь тоже калькирование,
и, наверно, это уже филум абстрактных машин.
Но&nbsp;это не&nbsp;точно, ведь речь и письмо
https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%BE[не&nbsp;всегда бывают осмысленными].

В общем, актуальное реальное (потоки, flux) мэпятся (автоматически) в виртуальное реальное (территорию),
затем из нее детерриториализируются универсумы (всё еще субъективные), и они уже «мэпятся» в абстрактные машины.
И, похоже, всё это может двигаться в&nbsp;обратном направлении и вообще в&nbsp;любых направлениях.

Подробнее можно послушать в лекции https://www.youtube.com/watch?v=KzpUfvFacoM[Фундаментальная психология. № 34],
либо начиная с тридцать второй.
