= Заметки
:toc: left
:icons: font

== Bash
=== Новый пользователь

Для генерации паролей удобно использовать `pwgen -s`.

Создание пользователя `qwerty` с&nbsp;группой `qwerty`,
башем в&nbsp;качестве шелла по-умолчанию
и&nbsp;с&nbsp;домашней директорией:

    U=qwerty
    G=$U

    groupadd $G
    useradd --create-home -s /bin/bash -g $G $U
    passwd $U

Запрет на&nbsp;чтение домашней директории другими пользователями:

    chmod 750 /home/$U


=== Скрыть юзернейм и&nbsp;хостнейм

Например, чтобы делать скриншоты и&nbsp;скринкасты для документации.

Приглашение баша определяется переменной `PS1`.
Чтобы скрыть имя пользователя и&nbsp;хост, но&nbsp;оставить текущее местоположение,
можно указать такой формат:

    PS1="\\w \$ "

Пример вывода:

```
~ $
~ $
~ $ cd folder/
~/folder $
~/folder $ cd anotherFolder
~/folder/anotherFolder $
```

Чтобы без лишних настроек получить чистое окно консоли:

    PS1="\\w \$ ";clear

Переменную `PS1` можно определить в `~/.bashrc`.
https://gahcep.github.io/blog/2012/07/28/unix-bash-shell-prompt/[Подробнее об&nbsp;этой переменной].

=== Освободить место

Когда забивается диск, перестают работать
самые базовые вещи. Даже клавиша TAB в&nbsp;баше.
Ничего нельзя доустановить, чтобы решить проблему.

Поэтому NCurses Disk Usage лучше устанавливать сразу после развёртывания сервера.

    sudo apt-get install ncdu

Программа рекурсивно сканирует папки и&nbsp;сортирует их
в&nbsp;порядке убывания размера.
Навигация как в&nbsp;mc, выход&nbsp;— q.

Когда место кончится:

. `df -h` чтобы понять, какие разделы переполнены.
. `ncdu` _из&nbsp;точки монтирования нужного раздела._

[NOTE]
====
Команда `ncdu` сканирует текущую директорию (working directory).
====

[NOTE]
====
Команда `ncdu` по-умолчанию не&nbsp;следует симлинкам.
====

[NOTE]
====
При использовании `ncdu` из&nbsp;корня файловой системы,
бывает полезно исключить примонтированные диски: `sudo ncdu --exclude=/media/* --exclude=/mnt/*`
====

=== Подсветка синтаксиса в&nbsp;less

В Ubuntu:

    sudo apt install source-highlight

Затем в `$HOME/.bashrc` добавить

```
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R -N'
```

[WARNING]
====
При открывании больших файлов могут появиться существенные задержки.
====

Опция `-N` необязательна. Она добавляет номера строк.

=== Шпаргалка по nano

Чтобы видеть номер текущей строки при редактировании:

    nano -c file.txt

Комбинации клавиш:

* Вырезать строку&nbsp;— CTRL+K.
* Вставить строку&nbsp;— CTRL+U.
* Undo&nbsp;— ALT+U или Esc+U (под M в справке подразумевается https://en.wikipedia.org/wiki/Meta_key[клавиша meta]).
* Redo&nbsp;— ALT+E или Esc+E.

=== Сканирование портов

Иногда nmap не может просканировать порты, т.к. устройство игнорирует пинг.

Там есть опция `-Pn`, чтобы не пинговать перед сканированием.

В строчке ниже сканируются порты с&nbsp;первого по&nbsp;сотый.

    nmap -p 1-100 -Pn 192.168.1.1

=== Бэкапы для несекретной информации

Должны обладать:

	- избыточностью;
	- простым чтением и&nbsp;навигацией;
	- простотой в&nbsp;удалении старых снапшотов.

Предлагаю использовать cron и&nbsp;tar.

На&nbsp;инстансе, откуда делаются бэкапы, _из-под рута_ настраивается
https://serverfault.com/questions/255084/simple-rsync-in-crontab-without-password[безпарольный доступ]
к&nbsp;файл-серверу по&nbsp;SSH.

Полагаю, если:

- файл-сервер находится в&nbsp;локальной сети,
- cron-задача на&nbsp;клиенте настроена из-под рута,
- публичный ключ на&nbsp;клиенте защищен от&nbsp;чтения другими пользователями,

то приватный ключ можно делать без парольной фразы.

Открытый ключ копируется на _сервер_ в _файл_ /home/USER/.ssh/authorized_keys.

Права:

    drwx------ (700) user user .ssh
    -rw------- (600) user user .ssh/authorized_keys

Может потребоваться изменить настройки SSH-сервера (разрешить publickey- или RSA-аутентификацию).
И&nbsp;нужно сделать reload SSH-сервера.

Затем, например, в `/usr/local/bin` клиента кладём скрипт
с&nbsp;правами `700 root:root` примерно следующего содержания:

    #!/bin/sh
    tar -cvpz --one-file-system -C "/путь/к/папке/" папка | ssh логин@сервер "(cat > /бэкапы/`date +\"%Y-%m-%dT%H.%M.%S\"`-названиеПапки.tar.gz)"

`sudo crontab -u root -e`

    0 0,6,12,18 * * * /usr/local/bin/myScript.sh

Проблема, которая тут может возникнуть — закончится место на файл-сервере.
В моём случае, это несущественно. Буду удалять старые снапшоты вручную время от времени.

=== Проверить файл на вирусы самым дешевым способом

```
sudo apt-get install clamav
```

```
clamscan файл
status=$?
```

А если нужно проверить целую папку, удобнее всего это сделать так:

```
clamscan --infected --recursive=yes папка
```

Предлагаю также увеличивать лимиты, чтобы при сканировании
не&nbsp;игнорировались файлы больше 25&nbsp;мегабайт:
`--max-filesize=4000m --max-scansize=4000m` (см. `man clamscan`).
Есть также опции для увеличения лимита
времени на&nbsp;файл (`--max-scantime`, по-умолчанию `120000` миллисекунд),
предела уровней вложенности директорий и&nbsp;т.д.

=== MD5 всех файлов в&nbsp;директории в&nbsp;Linux и&nbsp;FreeBSD

Во FreeBSD результат выводится в&nbsp;другом формате, нежели в Linux.

Команде

```
md5sum * > checklist.chk
```

во FreeBSD приблизительно соответствует команда

```
md5 -r * > checklist.chk
```

где `-r` означает &laquo;reversed&raquo;:
сначала хэш-сумма, потом имя файла.

И&nbsp;можно было&nbsp;бы сравнивать эти файлы хотя&nbsp;бы Meld'ом визуально,
если&nbsp;бы порядок строк не&nbsp;отличался.
Если я&nbsp;правильно понял, порядок glob зависит от&nbsp;переменной LC_COLLATE,
но&nbsp;мне не&nbsp;удалось сделать его одинаковым.
Поэтому я&nbsp;решил прибегнуть к&nbsp;универсальному средству&nbsp;&mdash;
к&nbsp;Перлу.

```
# Linux:
perl -e 'opendir DIR,"."; my @f = sort grep {!/^\.\.?$/} readdir(DIR); closedir DIR; foreach(@f) { print "\"$_\"\n"; }' | xargs md5sum > x.chk

# FreeBSD:
perl -e 'opendir DIR,"."; my @f = sort grep {!/^\.\.?$/} readdir(DIR); closedir DIR; foreach(@f) { print "\"$_\"\n"; }' | xargs md5 -r > x.chk

# Удобно сравнивать даже из консоли:
diff --ignore-space-change x1.chk x2.chk
colordiff --ignore-space-change x1.chk x2.chk

# Оба файла работают в Linux.
md5sum -c x1.chk
md5sum -c x2.chk

# Во FreeBSD (11.1-RELEASE) проверка MD5
# списка файлов не поддерживается.
```

Расшифровка однострочника:

```
# Открыть текущую директорию в handle с названием DIR.
opendir DIR,".";

# Справа налево:
# прочитать содержимое директории;
# убрать '.' и '..';
# отсортировать,
# сохранить в массив @f.
my @f = sort grep {!/^\.\.?$/} readdir(DIR);

# Закрыть директорию DIR.
closedir DIR;

# Вывести каждое имя файла с новой строки в кавычках.
foreach(@f) {
    print "\"$_\"\n";
}
```

Поддиректории игнорируются самими командами `md5` и `md5sum`.

=== Удалить конфиденциальные сведения из&nbsp;истории консоли

Конечно, можно удалить всю историю из&nbsp;текущего окна консоли (`history -c`),
но&nbsp;для многих ситуаций это может быть слишком радикальным шагом,
ведь есть возможность удалить отдельные строки из истории.

Вначале надо узнать идентификаторы последних команд.

```
history | tail -n 20
```

Затем удалить конкретные команды.

```
history -d идентификатор
```

Главное не&nbsp;забыть стереть в&nbsp;терминале результат первой команды.

```
clear
```

=== Выйти из&nbsp;sudo

Sudo позволяет не&nbsp;вводить пароль какое-то время после первого использования.
Это https://unix.stackexchange.com/questions/382060/change-default-sudo-password-timeout[настраивается].

Можно явно попрощаться, не&nbsp;закрывая окно терминала:

```
sudo -k
```

В следующий раз sudo снова спросит пароль.

== Linux UI

=== Адресная строка в&nbsp;Gnome Files

По-умолчанию, в файловом менеджере Gnome путь текущей папки показан
в виде последовательности кнопок. Чтобы переключиться на текстовое поле,
нужно нажать Ctrl+L.

Туда можно также ввести sftp-адрес.
Например, `sftp://username@192.168.0.1/folder`

== Здоровье

=== Эргономика рабочего места

Чтобы не https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BD%D0%B4%D1%80%D0%BE%D0%BC_%D0%B7%D0%B0%D0%BF%D1%8F%D1%81%D1%82%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D0%B0[сломать руку]
об&nbsp;мышку, рекомендую программу https://ru.wikipedia.org/wiki/Workrave[Workrave].
Она заставляет делать перерывы раз в&nbsp;три минуты по&nbsp;30 секунд и&nbsp;длинные перерывы время от&nbsp;времени.
Идея в&nbsp;том, чтобы убирать руки и&nbsp;вообще ничего ими не&nbsp;делать.

Минус: она может выбивать
из https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D1%82%D0%BE%D0%BA_(%D0%BF%D1%81%D0%B8%D1%85%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F)[состояния потока].

Иногда нужно просто проверить эргономику рабочего места.
Можно не&nbsp;заметить, что поза очень неудобная.

Я&nbsp;в&nbsp;очередной раз поменял всё, и&nbsp;вроде стало лучше. Привыкаю.
Текущие девайсы:

1. Кронштейны настенные https://www.kromax.ru/produce/plasma/3277/[KROMAX ATLANTIS-15] для мониторов (нет регулировки по&nbsp;высоте, к&nbsp;сожалению);
2. Стол с регулируемой высотой (ручной привод) SKARSTA СКАРСТА 120x70 см.
(похоже, он теперь называется https://www.ikea.com/ru/ru/p/trotten-trotten-stol-transf-bezhevyy-antracit-s29429586/[TROTTEN]);
3. https://www.ikea.com/ru/ru/p/loberget-loberget-blyskaer-blisker-rabochiy-stul-belyy-s39331867/[Стул на колёсиках LOBERGET ЛОБЕРГЕТ / BLYSKÄR БЛИСКЭР]
на&nbsp;винтовой опоре (по&nbsp;происшествии полугода могу сказать, что не&nbsp;самая удобная спинка,
и&nbsp;на&nbsp;нём накапливается статическое электричество, но&nbsp;стул точно удобнее нерегулируемого);
4. Любая вертикальная мышь. Я&nbsp;использую какую-то https://www.ozon.ru/product/mysh-provodnaya-870174-chernyy-172082323/?utm_campaign=productpage_link&utm_medium=share_button&utm_source=smm[NoName 870174 для правшей].
5. Большой тканевый коврик без подушки (я&nbsp;использую с&nbsp;подушкой, но&nbsp;она развёрнута в&nbsp;другую сторону).
Подушка помогала только первые пару недель. Вертикальная мышь намного лучше.
