= Заметки
:toc: left
:icons: font

== Bash
=== Скрыть юзернейм и&nbsp;хостнейм

Например, чтобы делать скриншоты и&nbsp;скринкасты для документации.

Приглашение баша определяется переменной `PS1`.
Чтобы скрыть имя пользователя и&nbsp;хост, но&nbsp;оставить текущее местоположение,
можно указать такой формат:

    PS1="\\w \$ "

Пример вывода:

```
~ $
~ $
~ $ cd folder/
~/folder $
~/folder $ cd anotherFolder
~/folder/anotherFolder $
```

Чтобы без лишних настроек получить чистое окно консоли:

    PS1="\\w \$ ";clear

Переменную `PS1` можно определить в `~/.bashrc`.
https://gahcep.github.io/blog/2012/07/28/unix-bash-shell-prompt/[Подробнее об&nbsp;этой переменной].

=== Освободить место

Когда забивается диск, перестают работать
самые базовые вещи. Даже клавиша TAB в&nbsp;баше.
Ничего нельзя доустановить, чтобы решить проблему.

Поэтому NCurses Disk Usage лучше устанавливать сразу после развёртывания сервера.

    sudo apt-get install ncdu

Программа рекурсивно сканирует папки и&nbsp;сортирует их
в&nbsp;порядке убывания размера.
Навигация как в&nbsp;mc, выход&nbsp;— q.

Когда место кончится:

. `df -h` чтобы понять, какие разделы переполнены.
. `ncdu` _из&nbsp;точки монтирования нужного раздела._

[NOTE]
====
Команда сканирует текущую директорию (working directory).
====

=== Подсветка синтаксиса в&nbsp;less

В Ubuntu:

    sudo apt install source-highlight

Затем в `$HOME/.bashrc` добавить

```
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R -N'
```

[WARNING]
====
При открывании больших файлов могут появиться существенные задержки.
====

Опция `-N` необязательна. Она добавляет номера строк.

=== Шпаргалка по nano

Чтобы видеть номер текущей строки при редактировании:

    nano -c file.txt

Комбинации клавиш:

* Вырезать строку&nbsp;— CTRL+K.
* Вставить строку&nbsp;— CTRL+U.
* Undo&nbsp;— ALT+U или Esc+U (под M в справке подразумевается https://en.wikipedia.org/wiki/Meta_key[клавиша meta]).
* Redo&nbsp;— ALT+E или Esc+E.

=== Сканирование портов

Иногда nmap не может просканировать порты, т.к. устройство игнорирует пинг.

Там есть опция `-Pn`, чтобы не пинговать перед сканированием.

В данном случае сканируются порты с 1 до 100.

    nmap -p 1-100 -Pn 192.168.1.1

=== Бэкапы для несекретной информации

Должны обладать:

	- избыточностью;
	- простым чтением и&nbsp;навигацией;
	- простотой в&nbsp;удалении старых снапшотов.

Предлагаю использовать cron и&nbsp;tar.

На десктопе _из-под рута_ настраивается
https://serverfault.com/questions/255084/simple-rsync-in-crontab-without-password[безпарольный доступ]
к&nbsp;файл-серверу по&nbsp;SSH.

Полагаю, если:

- сервак находится в&nbsp;локальной сети,
- клиентом является root,
- приватный ключ защищен от&nbsp;чтения другими пользователями,

то приватный ключ можно делать без парольной фразы.

Открытый ключ копируется на _сервер_ в _файл_ /home/USER/.ssh/authorized_keys.

Права:

    drwx------ (700) user user .ssh
    -rw------- (600) user user .ssh/authorized_keys

Может потребоваться изменить настройки SSH-сервера (разрешить publickey- или RSA-аутентификацию).
И&nbsp;нужно сделать reload SSH-сервера.

Затем, например, в `/usr/local/bin` клиента кладём скрипт
с&nbsp;правами `700 root:root` примерно следующего содержания:

    #!/bin/sh
    tar -cvpz --one-file-system -C "/путь/к/папке/" папка | ssh логин@сервер "(cat > /бэкапы/`date +\"%Y-%m-%dT%H.%M.%S\"`-названиеПапки.tar.gz)"

`sudo crontab -u root -e`

    0 0,6,12,18 * * * /usr/local/bin/myScript.sh

Проблема, которая тут может возникнуть — закончится место на файл-сервере.
В моём случае, это несущественно. Буду удалять старые снапшоты вручную время от времени.
