= Заметки
:toc: left
:icons: font

== Bash
=== Скрыть юзернейм и&nbsp;хостнейм

Например, чтобы делать скриншоты и&nbsp;скринкасты для документации.

Приглашение баша определяется переменной `PS1`.
Чтобы скрыть имя пользователя и&nbsp;хост, но&nbsp;оставить текущее местоположение,
можно указать такой формат:

    PS1="\\w \$ "

Пример вывода:

```
~ $
~ $
~ $ cd folder/
~/folder $
~/folder $ cd anotherFolder
~/folder/anotherFolder $
```

Чтобы без лишних настроек получить чистое окно консоли:

    PS1="\\w \$ ";clear

Переменную `PS1` можно определить в `~/.bashrc`.
https://gahcep.github.io/blog/2012/07/28/unix-bash-shell-prompt/[Подробнее об&nbsp;этой переменной].

=== Освободить место

Когда забивается диск, перестают работать
самые базовые вещи. Даже клавиша TAB в&nbsp;баше.
Ничего нельзя доустановить, чтобы решить проблему.

Поэтому NCurses Disk Usage лучше устанавливать сразу после развёртывания сервера.

    sudo apt-get install ncdu

Программа рекурсивно сканирует папки и&nbsp;сортирует их
в&nbsp;порядке убывания размера.
Навигация как в&nbsp;mc, выход&nbsp;— q.

Когда место кончится:

. `df -h` чтобы понять, какие разделы переполнены.
. `ncdu` _из&nbsp;точки монтирования нужного раздела._

[NOTE]
====
Команда сканирует текущую директорию (working directory).
====

=== Подсветка синтаксиса в&nbsp;less

В Ubuntu:

    sudo apt install source-highlight

Затем в `$HOME/.bashrc` добавить

```
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R -N'
```

[WARNING]
====
При открывании больших файлов могут появиться существенные задержки.
====

Опция `-N` необязательна. Она добавляет номера строк.

=== Шпаргалка по nano

Чтобы видеть номер текущей строки при редактировании:

    nano -c file.txt

Комбинации клавиш:

* Вырезать строку&nbsp;— CTRL+K.
* Вставить строку&nbsp;— CTRL+U.
* Undo&nbsp;— ALT+U или Esc+U (под M в справке подразумевается https://en.wikipedia.org/wiki/Meta_key[клавиша meta]).
* Redo&nbsp;— ALT+E или Esc+E.

=== Сканирование портов

Иногда nmap не может просканировать порты, т.к. устройство игнорирует пинг.

Там есть опция `-Pn`, чтобы не пинговать перед сканированием.

В строчке ниже сканируются порты с&nbsp;первого по&nbsp;сотый.

    nmap -p 1-100 -Pn 192.168.1.1

=== Бэкапы для несекретной информации

Должны обладать:

	- избыточностью;
	- простым чтением и&nbsp;навигацией;
	- простотой в&nbsp;удалении старых снапшотов.

Предлагаю использовать cron и&nbsp;tar.

На&nbsp;инстансе, откуда делаются бэкапы, _из-под рута_ настраивается
https://serverfault.com/questions/255084/simple-rsync-in-crontab-without-password[безпарольный доступ]
к&nbsp;файл-серверу по&nbsp;SSH.

Полагаю, если:

- файл-сервер находится в&nbsp;локальной сети,
- cron-задача на&nbsp;клиенте настроена из-под рута,
- приватный ключ на&nbsp;клиенте защищен от&nbsp;чтения другими пользователями,

то приватный ключ можно делать без парольной фразы.

Открытый ключ копируется на _сервер_ в _файл_ /home/USER/.ssh/authorized_keys.

Права:

    drwx------ (700) user user .ssh
    -rw------- (600) user user .ssh/authorized_keys

Может потребоваться изменить настройки SSH-сервера (разрешить publickey- или RSA-аутентификацию).
И&nbsp;нужно сделать reload SSH-сервера.

Затем, например, в `/usr/local/bin` клиента кладём скрипт
с&nbsp;правами `700 root:root` примерно следующего содержания:

    #!/bin/sh
    tar -cvpz --one-file-system -C "/путь/к/папке/" папка | ssh логин@сервер "(cat > /бэкапы/`date +\"%Y-%m-%dT%H.%M.%S\"`-названиеПапки.tar.gz)"

`sudo crontab -u root -e`

    0 0,6,12,18 * * * /usr/local/bin/myScript.sh

Проблема, которая тут может возникнуть — закончится место на файл-сервере.
В моём случае, это несущественно. Буду удалять старые снапшоты вручную время от времени.

== Параллели между информатикой, психологией и&nbsp;философией

Посмотрел, я, значит, видосы Александра Гельевича.

=== Объектно-ориентированная онтология

Меня зацепило название.
Но&nbsp;это слабо связанные вещи. ООП само появилось на&nbsp;полвека раньше.

Вот краткая предистория, чтобы было понятно, о&nbsp;чем это всё.

[WARNING]
====
Я не&nbsp;шарю в&nbsp;философии. Делайте поправку на&nbsp;это, читая ниженаписанное.
====

Философов в&nbsp;Римской империи можно упрощенно
разделить на&nbsp;неоплатоников
и https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D1%86%D1%8B_%D0%A6%D0%B5%D1%80%D0%BA%D0%B2%D0%B8[отцов церкви].
Причем христианская догматика сама тоже впитывала концепции платонизма и неоплатонизма (например, https://ru.wikipedia.org/wiki/Логос[Логос]).
Фредерик Коплстон в книге «История философии. Средние века» пишет, что положительная оценка
платонизма как приближения к&nbsp;истине
у&nbsp;христиан появляется уже во&nbsp;II&nbsp;веке&nbsp;н.э.

Тогда разделяли риторику,
философию как образ жизни (цинизм, стоицизм, эпикуреизм, платонизм, скептицизм),
христианский антропоцентризм и&nbsp;неоплатонизм как философскую школу.

https://ru.wikipedia.org/wiki/Аврелий_Августин[Аврелий Августин] придумал много крутых штук,
которые потом повлияют даже на&nbsp;Декарта.
Там за&nbsp;полторы тысячи лет много чего произошло.
Обо всем этом можно почитать тоже в&nbsp;книге Коплстона.
У&nbsp;меня реально не&nbsp;хватает терпения, чтобы это всё осилить.

Что важно. Из христианской догматики берется триадическая модель,
постепенно превращается в&nbsp;Бог-Субъект-Объект,
из&nbsp;нее потом Рене Декарт (Renatus Cartesius на&nbsp;латыни) выносит за&nbsp;скобки Бога.
Остается картезианский дуализм.
Вернуть туда Бога обратно пытается https://www.youtube.com/watch?v=9s4J2CUGWtE[Беркли].

Внутри дуализма больше ста лет спорят эмпиристы (всё мы узнаём из&nbsp;опыта)
и&nbsp;рационалисты (есть априорное знание).
Дэвид Юм&nbsp;— скорее эмпирик, говорит, какую бы идею мы не&nbsp;взяли,
всегда можно будет проследить ее связь с&nbsp;опытом.
А также, что мы не наблюдаем причинно-следственных связей,
следовательно за&nbsp;пределами нашей головы причинно-следственных связей нет.

Кант завершает спор эмпириков и&nbsp;рационалистов.
Он говорит, вот мы видим вещь.
Она в&nbsp;этот момент уже в&nbsp;нашем восприятии.
Мы не&nbsp;видим вещь саму по&nbsp;себе. Вот я&nbsp;вижу стол. Он у&nbsp;меня в&nbsp;голове.
Есть причина, по&nbsp;которой он у&nbsp;меня в&nbsp;голове&nbsp;— вещь сама по&nbsp;себе (ноумен).
Мы не&nbsp;можем ничего сказать про ноумен, потому что всё, что мы видим уже внутри нашего восприятия.
Возможно там нет стола или там что-то другое. Мы ничего не&nbsp;можем сказать.
Если ничто является причиной того, что я вижу стол, значит просто ноумен&nbsp;— это ничто.

Таким образом Кант запирает философию внутри восприятия, а&nbsp;еще точнее внутри взаимосвязи (корреляции)
«человек — мир». В&nbsp;начале XXI века спекулятивные реалисты дают этому явлению название «корреляционизм»,
а&nbsp;своей задачей ставят его преодоление.

При этом они разделяют

* слабый корреляционизм&nbsp;— мы всё-таки можем описать ноумен, но неспособны объяснить,
почему он таков, какой он есть (Гуссерль, ранний Витгенштейн, Хабермас);
* сильный корреляционизм&nbsp;— мы не&nbsp;можем описать ноумен, т.к. то,
через что мы его воспринимаем, произвольно, зависит от&nbsp;конкретной культуры
(Хайдеггер, поздний Витгенштейн, постмодернизм).

Сюда же относится http://www.logosjournal.ru/arch/95/118_10.pdf[аргумент «Перла»], сформулированный Беркли:
«Нельзя познать независимую от&nbsp;разума реальность,
не&nbsp;познавая ее. Следовательно, нельзя познать независимую от&nbsp;разума реальность».

И спекулятивные реалисты указывают на&nbsp;еще одну проблему современной философии&nbsp;—
на&nbsp;философии привилегированного доступа&nbsp;—
наделение человека привилегиями по&nbsp;сравнению с&nbsp;другими предметами.

Собственно, ООО&nbsp;— это одна из&nbsp;философий спекулятивного реализма.

=== Шизоанализ

В&nbsp;психологии под виртуальным реальным подразумевается не&nbsp;то,
что мы обычно называем виртуальной реальностью,
а&nbsp;реальное, представленное в психике, поэтому оно виртуальное.

В&nbsp;шизоанализе Феликса Гваттари, виртуальное реальное (экзистенциальная территория)&nbsp;—
это психотический хаос в психике, ощущаемый, переживаемый непосредственно.
Т.е. он включает в&nbsp;себя всё ощущаемое, даже иллюзии, фантазии, видения, _находящиеся здесь_.
Психика выделяет из&nbsp;него некоторые структуры, называемые универсумами.
Это платоновские идеи наоборот. Не&nbsp;идеи предшествующие вещам, а&nbsp;идеи выделяемые из&nbsp;территории,
псевдо-вечные понятия, т.е. некоторые обобщения.
Затем эти универсумы могут быть выражены в&nbsp;абстрактных машинах.

Так вот, например, программист выражает универсумы в&nbsp;виде абстрактных машин и, возможно,
создаёт новые универсумы из&nbsp;переживаемого хаоса.

В&nbsp;лекциях много раз упоминается частичные объекты, но
вначале он указывает на&nbsp;понятие https://fr.wikipedia.org/wiki/Objet_(psychanalyse)#Objet_partiel[part-object],
введенное последователями https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D1%8F%D0%B9%D0%BD,_%D0%9C%D0%B5%D0%BB%D0%B0%D0%BD%D0%B8[Мелани Кляйн],
затем называет то&nbsp;же самое https://en.wikipedia.org/wiki/Comfort_object[транзитивными объектами], частями без целого,
https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B4%D1%83%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D0%B7%D0%BC[антихолистскими] структурами,
противопоставляя однако их делимость и&nbsp;макроскопичность https://ru.wikipedia.org/wiki/%D0%90%D1%82%D0%BE%D0%BC%D0%B8%D0%B7%D0%BC[атомам Демокрита].
Я обратил внимание, что в&nbsp;абсолютном большинстве современных языков программирования, все объекты&nbsp;—
части, предшествующие целому, изначально не&nbsp;являющиеся частью ничего:
существуют в&nbsp;куче, соединяются через указатели.

Кстати, выражение универсумов на&nbsp;обычном человеческом языке&nbsp;— это ведь тоже калькирование,
и, наверно, уже относится к абстрактным машинам.
Но&nbsp;это не&nbsp;точно, ведь речь и письмо
https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%BE[не&nbsp;всегда бывают осмысленными].

В общем, актуальное реальное (потоки, flux) мэпятся (автоматически) в виртуальное реальное (территорию),
затем из нее детерриториализируются универсумы (всё еще субъективные), и они уже «мэпятся» в абстрактные машины.
И, похоже, всё это может двигаться в&nbsp;обратном направлении и вообще в&nbsp;любых направлениях.

Подробнее можно послушать в лекции https://www.youtube.com/watch?v=KzpUfvFacoM[Фундаментальная психология. № 34],
либо начиная с тридцать второй.
